version: '2.1'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb-host_data:/bitnami/mariadb'
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '8080:8080'
#      - '8443:8443'
    restart: always
    depends_on:
      - mariadb
volumes:
  mariadb-host_data:
    driver: local
